'use client'

import { Mail, Check } from 'lucide-react'
import { Button } from '@/app/components/ui/Button'
import { Modal, ModalHeader, ModalBody, ModalFooter } from '@/app/components/ui/Modal'
import { SourceBadge } from './NovaPrimitives'
import { SOURCE_LABEL, type ReportSection } from '@/app/lib/onboarding/nova-onboarding-data'

interface NovaReportModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  companyName: string
  sections: ReportSection[]
  emailed: boolean
  onEmail: () => void
}

/** The first operational report. Sections are split by source so the user
 * can always tell what Nova knows, what's in UpKeep, what came from their
 * apps, and what Nova is inferring. */
export function NovaReportModal({ open, onOpenChange, companyName, sections, emailed, onEmail }: NovaReportModalProps) {
  return (
    <Modal open={open} onOpenChange={onOpenChange} maxWidth="640px">
      <ModalHeader title={`${companyName} · Operational report`} description="Generated by Nova · public sources and connected apps" />
      <ModalBody className="flex flex-col gap-[var(--space-lg)]">
        {sections.map((section, i) => (
          <section key={section.source} className="flex flex-col gap-2 nova-enter" style={{ animationDelay: `${i * 100}ms` }}>
            <div className="flex items-center justify-between">
              <h4 className="text-[length:var(--font-size-base)] font-semibold text-[var(--color-neutral-12)]">{section.title}</h4>
              <span className="text-[length:var(--font-size-xs)] font-medium uppercase tracking-[0.04em] text-[var(--color-neutral-8)]">{SOURCE_LABEL[section.source]}</span>
            </div>
            <ul className="flex flex-col gap-1.5">
              {section.items.map(item => (
                <li key={item.text} className="flex items-center justify-between gap-3 rounded-[var(--radius-lg)] bg-[var(--color-neutral-2)] px-3 py-2">
                  <span className="text-[length:var(--font-size-base)] text-[var(--color-neutral-11)]">{item.text}</span>
                  {item.app && <SourceBadge source={item.source} app={item.app} />}
                </li>
              ))}
            </ul>
          </section>
        ))}
      </ModalBody>
      <ModalFooter className="justify-end border-t border-[var(--border-subtle)]">
        <Button variant="secondary" size="md" onClick={onEmail} disabled={emailed}>
          {emailed ? <><Check size={14} /> Sent</> : <><Mail size={14} /> Email me the report</>}
        </Button>
        <Button variant="primary" size="md" onClick={() => onOpenChange(false)}>What should I do next?</Button>
      </ModalFooter>
    </Modal>
  )
}
